### ISSUE TITLE
Git Commit & PR 작성 언어

### ISSUE THREAD

**Issue by HanSJin** [iOSTube/iOSTube#9]
## Let's talk about Language
Git Commit Message 혹은 PR 을 작성할 때 한글로 적을까요? 영어로 적을까요?
@ThroughKim @devleeyang @hyunable 
각자 의견좀 주세요 :)

**Comment by ThroughKim** [comment]
영어에 한표 ㅋㅋ

**Comment by devleeyang** [comment]
의사소통을 위해.... 한글쓰

**Comment by HanSJin** [comment]
영어 코멘트가 사실 쓰는 입장에서 유쾌하지는 않은것 같아요.
근데 우리가 만드는게 결국 오픈소스로 간다면 영어는 필수이기는 해요;;;
한편으로는 영어 작문의 스트레스가 프로젝트 흥미 저하로 이뤄질까하는 걱정도 됩니다.
아무튼 제 의견은 한글..

**Comment by devleeyang** [comment]
저도 위의 의견으로 공감입니당. 오히려 커밋이 더 헷갈릴수도있어여 짧은 작문실력으로 인해

**Comment by HanSJin** [comment]
@devleeyang 너무 빠른 클로즈인데요~ㅠ  
스루찡 혀나찡 의견 더 듣고파요 ~

**Comment by devleeyang** [comment]
아......=_= 뭔가 클로즈누른거같은데 잘못본겟지 햇더니 정말 눌렀네요 죄송함돠

**Comment by ThroughKim** [comment]
오픈소스를 염두해두고 영어로 하자는 의견을 제시한거였는데, 승쨩 의견 보고나니 플젝 초기에는 한글로 하는 편이 나을 것 같다는 생각이 드네요

**Comment by hyunable** [comment]
구지 나눠야 하는가라고 생각듭니당. 큰 컨벤션만 맞춰도 상관없을 것 같은게 누군가는 영어로 커밋멘트쓰는 것이 편하거나 연습을 하고 싶어 할 수 있고, 누군가는 그게 스트레스로 다가올 수 있는데 구지 맞추지 않아도 
`Feature: 내용` 혹은 `Refactor: 내용` 이런식으로 커밋멘트 컨벤션만 맞춰도 좋다고 생각합니당.

**Comment by HanSJin** [comment]
네 그럼 README 에 언급된 커밋 컨벤션 가이드를 따르는 선에서 언어 정도는 개인의 자유로요!
일단 이 이슈는 `Close` 하겠습니다. 또 필요하면 열어주세요
